[package]
name = "discorder"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.4.2", features = ["derive"] }
reqwest = { version = "0.11.20", features = ["blocking", "json", "multipart"] }
